# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20160822_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(default='PD', max_length=4),
        ),
    ]
