# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_machine'),
        ('problem', '0005_auto_20160822_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='machine',
            field=models.ForeignKey(default='judge001', on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='judge.Machine', to_field='name'),
            preserve_default=False,
        ),
    ]
