# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_submission_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='judge.Machine', to_field='name'),
        ),
    ]
