# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_auto_20160825_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='limit',
            name='language',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
