# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0010_invalidword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')], default=1),
        ),
        migrations.AlterField(
            model_name='description',
            name='status',
            field=models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')], default=1),
        ),
        migrations.AlterField(
            model_name='limit',
            name='status',
            field=models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')], default=1),
        ),
        migrations.AlterField(
            model_name='metaproblem',
            name='status',
            field=models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')], default=1),
        ),
        migrations.AlterField(
            model_name='node',
            name='status',
            field=models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')], default=1),
        ),
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')], default=1),
        ),
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')], default=1),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='status',
            field=models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')], default=1),
        ),
    ]
