# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_machine'),
        ('problem', '0010_invalidword'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialJudge',
            fields=[
                ('creator', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('introduction', models.CharField(max_length=512, null=True)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='specialjudge', serialize=False, to='problem.Problem')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialjudge', to='judge.Environment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
