# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 04:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('creator', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')])),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('detail', models.CharField(max_length=256)),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField()),
                ('cmd_queue', models.CharField(max_length=32)),
                ('data_queue', models.CharField(max_length=32)),
                ('environment', models.ManyToManyField(related_name='machine', to='judge.Environment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
