# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='status',
            field=models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')], default=1),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')], default=1),
        ),
    ]
