# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('creator', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')])),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
