# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20160827_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
