# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_last_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_str',
            field=models.CharField(default='abcde', max_length=128),
            preserve_default=False,
        ),
    ]
