# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_id_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_str',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
