# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0014_auto_20160828_2353'),
        ('client', '0005_auto_20160913_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='category',
            field=models.ManyToManyField(related_name='client', to='problem.Category'),
        ),
    ]
