# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('creator', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('introduction', models.CharField(max_length=512, null=True)),
                ('status', models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')])),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('number_problem', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetaProblem',
            fields=[
                ('creator', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('introduction', models.CharField(max_length=512, null=True)),
                ('source', models.CharField(max_length=256, null=True)),
                ('author', models.CharField(max_length=32, null=True)),
                ('status', models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')])),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number_description', models.IntegerField(default=0)),
                ('number_sample', models.IntegerField(default=0)),
                ('number_test_data', models.IntegerField(default=0)),
                ('number_virtual_judge', models.IntegerField(default=0)),
                ('number_problem', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('creator', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('introduction', models.CharField(max_length=512, null=True)),
                ('status', models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')])),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('number_problem', models.IntegerField(default=0)),
                ('meta_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample', to='problem.MetaProblem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('creator', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('introduction', models.CharField(max_length=512, null=True)),
                ('status', models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')])),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('in_size', models.IntegerField()),
                ('out_size', models.IntegerField()),
                ('number_problem', models.IntegerField(default=0)),
                ('meta_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_data', to='problem.MetaProblem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VirtualJudge',
            fields=[
                ('creator', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('introduction', models.CharField(max_length=512, null=True)),
                ('status', models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')])),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number_problem', models.IntegerField(default=0)),
                ('meta_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_judge', to='problem.MetaProblem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='description',
            name='meta_problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='problem.MetaProblem'),
        ),
    ]
