# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 12:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judge', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('creator', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('introduction', models.CharField(max_length=512, null=True)),
                ('source', models.CharField(max_length=256, null=True)),
                ('author', models.CharField(max_length=32, null=True)),
                ('status', models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')])),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number_node', models.IntegerField(default=0)),
                ('number_problem', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('creator', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('introduction', models.CharField(max_length=512, null=True)),
                ('status', models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')])),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(null=True)),
                ('number_problem', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('creator', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('introduction', models.CharField(max_length=512, null=True)),
                ('status', models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')])),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time_limit', models.IntegerField(default=-1)),
                ('memory_limit', models.IntegerField(default=-1)),
                ('length_limit', models.IntegerField(default=-1)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit', to='judge.Environment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetaProblem',
            fields=[
                ('creator', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('introduction', models.CharField(max_length=512, null=True)),
                ('source', models.CharField(max_length=256, null=True)),
                ('author', models.CharField(max_length=32, null=True)),
                ('status', models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')])),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number_description', models.IntegerField(default=0)),
                ('number_sample', models.IntegerField(default=0)),
                ('number_test_data', models.IntegerField(default=0)),
                ('number_virtual_judge', models.IntegerField(default=0)),
                ('number_problem', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('creator', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('introduction', models.CharField(max_length=512, null=True)),
                ('status', models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')])),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number_node', models.IntegerField(default=0)),
                ('number_problem', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node', to='problem.Category')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='problem.Node')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('creator', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('introduction', models.CharField(max_length=512, null=True)),
                ('source', models.CharField(max_length=256, null=True)),
                ('author', models.CharField(max_length=32, null=True)),
                ('status', models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')])),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('test_type', models.CharField(choices=[('normal', 'normal'), ('ignBlank', 'ignore blank'), ('ignPunct', 'ignore punctuation')], default='normal', max_length=8)),
                ('number_test_data', models.IntegerField(default=0)),
                ('number_virtual_judge', models.IntegerField(default=0)),
                ('number_decorator', models.IntegerField(default=0)),
                ('number_limit', models.IntegerField(default=0)),
                ('number_category', models.IntegerField(default=0)),
                ('number_node', models.IntegerField(default=0)),
                ('description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='problem.Description')),
                ('meta_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='problem.MetaProblem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProblemCategoryNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_relation', to='problem.Category')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_relation', to='problem.Node')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_relation', to='problem.Problem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProblemTestData',
            fields=[
                ('creator', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_data_relation', to='problem.Problem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProblemVirtualJudge',
            fields=[
                ('creator', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_judge_relation', to='problem.Problem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('creator', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('introduction', models.CharField(max_length=512, null=True)),
                ('status', models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')])),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(null=True)),
                ('number_problem', models.IntegerField(default=0)),
                ('meta_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample', to='problem.MetaProblem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=128, null=True)),
                ('extra', models.CharField(max_length=128, null=True)),
                ('language', models.CharField(max_length=32)),
                ('result', models.CharField(choices=[('PD', 'Pending'), ('RPD', 'Pending Rejudge'), ('DC', 'Decorating'), ('CP', 'Compiling'), ('RN', 'Running'), ('JG', 'Judging'), ('RJ', 'Running & Judging'), ('IW', 'Invalid Word'), ('RF', 'Restrained Function'), ('DF', 'Decoration Failed'), ('CLLE', 'Code Length Limit Exceeded'), ('CE', 'Compile Error'), ('AC', 'Accepted'), ('PE', 'Presentation Error'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('OLE', 'Output Limit Exceeded'), ('RE', 'Runtime Error'), ('SE', 'Submission Error'), ('UE', 'Unknown Error')], default='PD', max_length=4)),
                ('result_type', models.CharField(default='WT', max_length=2)),
                ('memory', models.IntegerField(null=True)),
                ('time', models.IntegerField(null=True)),
                ('code_length', models.IntegerField(null=True)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('last_judge_time', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='client.Client', to_field='name')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='judge.Environment')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='problem.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', django.contrib.postgres.fields.jsonb.JSONField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code', to='problem.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionTestInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('test_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_info', to='problem.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('creator', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('introduction', models.CharField(max_length=512, null=True)),
                ('status', models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')])),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('in_size', models.IntegerField(default=0)),
                ('out_size', models.IntegerField(default=0)),
                ('number_problem', models.IntegerField(default=0)),
                ('meta_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_data', to='problem.MetaProblem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VirtualJudge',
            fields=[
                ('creator', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('introduction', models.CharField(max_length=512, null=True)),
                ('status', models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')])),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number_problem', models.IntegerField(default=0)),
                ('meta_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_judge', to='problem.MetaProblem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='problemvirtualjudge',
            name='virtual_judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_relation', to='problem.VirtualJudge'),
        ),
        migrations.AddField(
            model_name='problemtestdata',
            name='test_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_relation', to='problem.TestData'),
        ),
        migrations.AddField(
            model_name='problem',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='problem.Sample'),
        ),
        migrations.AddField(
            model_name='problem',
            name='test_data',
            field=models.ManyToManyField(related_name='problem', through='problem.ProblemTestData', to='problem.TestData'),
        ),
        migrations.AddField(
            model_name='problem',
            name='virtual_judge',
            field=models.ManyToManyField(related_name='problem', through='problem.ProblemVirtualJudge', to='problem.VirtualJudge'),
        ),
        migrations.AddField(
            model_name='node',
            name='problem',
            field=models.ManyToManyField(related_name='node', through='problem.ProblemCategoryNode', to='problem.Problem'),
        ),
        migrations.AddField(
            model_name='limit',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit', to='problem.Problem'),
        ),
        migrations.AddField(
            model_name='description',
            name='meta_problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='problem.MetaProblem'),
        ),
        migrations.AddField(
            model_name='category',
            name='problem',
            field=models.ManyToManyField(related_name='category', through='problem.ProblemCategoryNode', to='problem.Problem'),
        ),
    ]
