# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 12:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20160816_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('web_client', models.CharField(max_length=32, null=True)),
                ('user', models.CharField(max_length=32)),
                ('environment', models.CharField(max_length=32, null=True)),
                ('language', models.CharField(max_length=32)),
                ('result', models.CharField(default='PD', max_length=4)),
                ('result_type', models.CharField(default='WT', max_length=2)),
                ('memory', models.IntegerField(null=True)),
                ('time', models.IntegerField(null=True)),
                ('code_length', models.IntegerField(null=True)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('last_judge_time', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='problem.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('code', models.TextField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code', to='problem.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_info', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='test_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='problem.SubmissionTest'),
        ),
    ]
