# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20160816_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='result',
            field=models.CharField(default='PD', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='result_type',
            field=models.CharField(default='WT', max_length=2, null=True),
        ),
    ]
