# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 12:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('creator', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')])),
                ('eid', models.CharField(help_text='供各Judge机决定编译方式的唯一标识符。', max_length=16, primary_key=True, serialize=False, unique=True)),
                ('language', models.CharField(help_text='阅读题目以及提交题目时对外显示的编程环境名称。', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('creator', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')])),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('detail', models.CharField(max_length=256)),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField()),
                ('environment', models.ManyToManyField(related_name='machine', to='judge.Environment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
