# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('creator', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'available'), (0, 'unavailable')])),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('eid', models.CharField(help_text='供各Judge机决定编译方式的唯一标识符。', max_length=16, unique=True)),
                ('language', models.CharField(help_text='阅读题目以及提交题目时对外显示的编程环境名称。', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
